## Acessar o arquivo com a base de dados.
* Acesse o link https://www.kaggle.com/datasets/namespaiva/base-varejo/data
* Faça o download do arquivo base-varejo.zip
* Instalar as bibliotecas Pandas e Numpy, auxiliares ao Python
* Extrair os arquivos da pasta .zip com a base de dados na pasta raiz do projeto

In [29]:
# Instalar a biblioteca Pandas, auxiliar ao Python
%pip install -q pandas

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [30]:
# Instalar a biblioteca Numpy, auxiliar ao Python
%pip install -q numpy

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [31]:
# Inserir todos os imports necessários para o projeto
import pandas as pd
import numpy as np

In [47]:
# Carregar o arquivo CSV com os dados do projeto
df = pd.read_csv(r"C:\Users\LUIZ HENRIQUE\sesi_senai\mini_projeto_turma05\Base Varejo.csv", sep=";")
df.head() # Exibir as primeiras linhas do DataFrame para verificar se os dados foram carregados corretamente

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

In [48]:
# Exibir informações sobre o DataFrame, como número de linhas, colunas e tipos de dados
# Ponto de atenção: Os valores da coluna DATA estão como string. É necessário converter para o tipo datetime.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  str
 1   CO_ID        830000 non-null  int64
 2   CL_ID        830000 non-null  int64
 3   CL_GENERO    830000 non-null  str
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  str
 7   PR_ID        830000 non-null  int64
 8   PR_CAT       830000 non-null  str
 9   PR_NOME      830000 non-null  str
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: float64(4), int64(5), str(5)
memory usage: 88.7 MB

In [49]:
# Converter a coluna 'DATA' para o tipo datetime
df['DATA'] = pd.to_datetime(df['DATA'], format='%d/%m/%Y', errors='coerce')
df.info() # Confirmar que a conversão foi bem-sucedida e que a coluna 'DATA' agora está no formato datetime.
df.head() # Exibir linhas para confirmar que a coluna 'DATA' foi convertida corretamente.

<class 'pandas.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  datetime64[us]
 1   CO_ID        830000 non-null  int64
 2   CL_ID        830000 non-null  int64
 3   CL_GENERO    830000 non-null  str
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  str
 7   PR_ID        830000 non-null  int64
 8   PR_CAT       830000 non-null  str
 9   PR_NOME      830000 non-null  str
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: datetime64[us](1), float64(4), int64(5), str(4)
memory usage: 88.7 MB

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,2019-02-01,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,2019-02-01,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,2019-02-01,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,2019-02-01,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,2019-02-01,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

Através do método df.info() foi possível identificar que há 4 colunas inválidas no DataFrame.
São elas: Unnamed: 10, Unnamed: 11, Unnamed: 12 e Unnamed: 13.

In [50]:
# Retirar as colunas que não serão utilizadas na análise
df = df.drop(columns=["Unnamed: 10", "Unnamed: 11", "Unnamed: 12", "Unnamed: 13"])

In [51]:
# Exibir o número de linhas e colunas do DataFrame após a remoção das colunas inválidas
df.shape

(830000, 10)

In [52]:
# Verificar se há registros ausentes no DataFrame
df.isna().sum()

DATA         0
CO_ID        0
CL_ID        0
CL_GENERO    0
CL_EC        0
CL_FHL       0
CL_SEG       0
PR_ID        0
PR_CAT       0
PR_NOME      0
dtype: int64

In [53]:
# Verificar se há registros nulos no DataFrame
df.isnull().sum()

DATA         0
CO_ID        0
CL_ID        0
CL_GENERO    0
CL_EC        0
CL_FHL       0
CL_SEG       0
PR_ID        0
PR_CAT       0
PR_NOME      0
dtype: int64

In [54]:
# Exibir estatísticas descritivas do DataFrame, como média, desvio padrão, valores mínimo e máximo, entre outros
display(df.describe())

,DATA,CO_ID,CL_ID,CL_EC,CL_FHL,PR_ID
count,830000,830000.00000,830000.000000,830000.000000,830000.00000,830000.000000
mean,2020-12-06 14:55:46.421204,460045.08989,499.595204,2.596911,1.14654,115.051855
min,2019-01-04 00:00:00,1000.00000,1.000000,1.000000,0.00000,1.000000
25%,2020-01-09 00:00:00,233117.00000,254.000000,2.000000,0.00000,58.000000
50%,2020-12-27 00:00:00,456517.00000,498.000000,3.000000,0.00000,115.000000
75%,2021-10-20 00:00:00,690132.00000,746.000000,4.000000,2.00000,172.000000
max,2022-12-08 00:00:00,919822.00000,1000.000000,5.000000,4.00000,229.000000
std,NaN,265465.24754,287.568253,1.170599,1.41696,66.129241

In [55]:
# Exibir os registros onde a coluna "PR_NOME" possui o valor "N/D" para identificar possíveis inconsistências nos dados
display(df[df["PR_NOME"] == "#N/D"])

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
82,2019-02-01,1078,290,F,1,0,B,107,#N/D,#N/D
223,2019-02-01,1103,957,M,2,3,B,107,#N/D,#N/D
640,2019-02-01,1482,453,F,1,0,B,107,#N/D,#N/D
857,2019-02-01,1683,438,F,1,0,B,107,#N/D,#N/D
917,2019-02-01,1793,608,F,3,0,C,107,#N/D,#N/D
...,...,...,...,...,...,...,...,...,...,...
829528,2022-08-19,919578,567,F,1,0,C,107,#N/D,#N/D
829602,2022-08-19,919626,758,F,3,0,B,107,#N/D,#N/D
829787,2022-08-19,919716,801,M,1,4,B,107,#N/D,#N/D
829829,2022-08-19,919716,801,M,1,4,B,107,#N/D,#N/D
829882,2022-08-19,919770,888,F,4,2,B,107,#N/D,#N/D

Através do método display() acima, foi possível verificar que 3650 linhas do DataFrame possuem registro com valor "#N/D" nas colunas "PR_CAT" e "PR_NOME"

In [56]:
# Descartar os registros onde a coluna "PR_NOME" possui o valor "N/D" para evitar inconsistências na análise
df[["PR_CAT", "PR_NOME"]] = df[["PR_CAT", "PR_NOME"]].replace("#N/D", np.nan)
df = df.dropna(subset=["PR_CAT", "PR_NOME"])

In [57]:
# Exibir o número de linhas e colunas do DataFrame após a remoção dos registros inválidos
df.shape

(826350, 10)

No arquivo .zip encontramos também um arquivo .pdf no qual podemos verificar o que cada coluna do DataSet significa.
Aplicar uma nova nomenclatura para que fique mais fácil a nossa leitura dos dados:

CO_ID     -> ID_COMPRA  
CL_ID     -> ID_CLIENTE  
CL_GENERO -> GENERO_CLIENTE  
CL_EC     -> ESTADO_CIVIL  
CL_FHL    -> FILHOS_CLIENTE  
CL_SEG    -> CLASSE_ECONOMICA_CLIENTE  
PR_ID     -> ID_PRODUTO  
PR_CAT    -> CATEGORIA_PRODUTO  
PR_NOME   -> NOME_PRODUTO

In [59]:
# Renomear as colunas conforme a convenção acima
df = df.rename(columns={
    "CO_ID": "ID_COMPRA",
    "CL_ID": "ID_CLIENTE",
    "CL_GENERO": "GENERO_CLIENTE",
    "CL_EC": "ESTADO_CIVIL",
    "CL_FHL": "FILHOS_CLIENTE",
    "CL_SEG": "CLASSE_ECONOMICA_CLIENTE",
    "PR_ID": "ID_PRODUTO",
    "PR_CAT": "CATEGORIA_PRODUTO",
    "PR_NOME": "NOME_PRODUTO",
})
# Verificar as colunas do DataFrame após a renomeação
df.head()

,DATA,ID_COMPRA,ID_CLIENTE,GENERO_CLIENTE,ESTADO_CIVIL,FILHOS_CLIENTE,CLASSE_ECONOMICA_CLIENTE,ID_PRODUTO,CATEGORIA_PRODUTO,NOME_PRODUTO
0,2019-02-01,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA
1,2019-02-01,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS
2,2019-02-01,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO
3,2019-02-01,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
4,2019-02-01,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO